// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"rest-gin-gorm/product"
)

// Injectors from wire.go:

func initProductAPI(db *gorm.DB) product.ProductAPI {
	productRepository := product.ProvideProductRepository(db)
	productService := product.ProvideProductService(productRepository)
	productAPI := product.ProvideProductAPI(productService)
	return productAPI
}
